[package]
name = "web"
version = "0.1.0"
authors = ["李文广 <liwenguang@lwgs-macpro.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
